nacos:
  config:
    bootstrap:
      enable: true
    data-ids: people,test
    group: DEVELOP
    type: yaml
    auto-refresh: true
    max-retry: 10
    config-retry-time: 2333
    config-long-poll-timeout: 46000
    enable-remote-sync-config: true
    username: nacos
    password: nacos
    ext-config[0]:
      data-id: nacos.log.test
      group: LOG_DEVELOP
      max-retry: 10
      type: properties
      auto-refresh: true
      config-retry-time: 2333
      config-long-poll-timeout: 46000
      enable-remote-sync-config: true

server:
  port: 10011

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always